-- First, delete from the ORDER_LINE table
DELETE FROM ORDER_LINE
WHERE ORDER_ID IN (SELECT ORDER_ID FROM ORDERT WHERE CUSTOMER_ID = 10001);

-- Then, delete from the ORDERT table
DELETE FROM ORDERT
WHERE CUSTOMER_ID = 10001;

-- Finally, delete from the CUSTOMER table
DELETE FROM CUSTOMER
WHERE CUSTOMER_ID = 10001;

-- Select all records from the CUSTOMER table
SELECT * FROM CUSTOMER,ORDERT,ORDER_LINE;

